[project]
name = "iitm-dvd-backend"
version = "1.0.0"
requires-python = ">=3.10, <3.13"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "uvicorn[standard]>=0.30.0",
    "pandas>=2.2.0",
    "numpy>=1.26.4,<2.2.0",
    "python-dotenv>=1.0.0"
]

[tool.setuptools.packages.find]
include = ["app*", "integration*"]
